### ISSUE TITLE
UI - Disable bottom bar hide effect

### ISSUE THREAD

**Issue by drJAGartner** [Sotera/genie-ui#47]
The bottom control panel become partially hidden when it is double clicked.  This has causes user interaction errors.  We need to disable the double click action that hides this panel.  As a part of this fix, the panel partially overlaps the map.  We should reduce the map area to reflect that the bottom block is now a fixed height.

**Comment by lukewendling** [comment]
@drJAGartner ready for review

**Comment by drJAGartner** [comment]
Fixed
