### ISSUE TITLE
Drill Down - Reveal location of individual tweets/post by clicking side bar

### ISSUE THREAD

**Issue by drJAGartner** [Sotera/genie-ui#50]
Once data about individual tweet/photos/rss stories are properly associated with events, we need to provide data through the UI.  This will be accessed by clicking the side panel which organizes the individual genie event objects.

**Comment by lukewendling** [comment]
@drJAGartner ready for review

click on twitter icon to see individual tweet

**Comment by drJAGartner** [comment]
Looks good.
