### ISSUE TITLE
UI - Improve photo browsing in sandbox clusters

### ISSUE THREAD

**Issue by drJAGartner** [Sotera/genie-ui#52]
The current method has us hovering over graph nodes, and the picture is moved from a top bar to a bottom bar, and populated within the cluster.  We should:
* removed both the top & bottom bars
* Use the large area in the lower right (where the word cloud typically appears) to show the image larger and more clearly
* make the image on the map smaller to give a more grainular depiction of where the picture took place.

**Comment by lukewendling** [comment]
@drJAGartner i'm not sure we'll like the result of removing both image grids. without the top grid, when u select an event, you'll only see the network graph. then you have to hover the tiny dots to see a picture. let me start this by removing just the bottom grid first.

**Comment by drJAGartner** [comment]
That makes sense, we'll see how it looks.

**Comment by lukewendling** [comment]
@drJAGartner ready for review... with regard to last Fri discussion with Chris C.

**Comment by drJAGartner** [comment]
Looks good, but perhaps we can make the images bigger in the lower right, at the cost of having a smaller que.
