### ISSUE TITLE
UI - Heatmap clustering at wide zoom

### ISSUE THREAD

**Issue by drJAGartner** [Sotera/genie-ui#54]
At zoom levels where we are using the heatmap, if the number of events is below some threashold (try 200) we should simply feed in every genie event to the heatmap, not cluster.

**Comment by lukewendling** [comment]
@justinlueders is this still a concern since we're now using dbscan to cluster?

cc @drJAGartner

**Comment by justinlueders** [comment]
@drJAGartner @lukewendling 

no we use all events all the time now with a min dbscan cluster size of 1.

**Comment by drJAGartner** [comment]
I think is resolved by the focus on event.
