### ISSUE TITLE
UI - remove heat indicators with zoom in

### ISSUE THREAD

**Issue by drJAGartner** [Sotera/genie-ui#55]
As we zoom into areas of interest, we need to drop the heat map images, and display sandbox areas/twitter pins/watchmen pins

**Comment by lukewendling** [comment]
@drJAGartner ready for review. The map auto-hides heat markers at zoom level 11 (you can see the level in the URL ../z/11/c... for instance)

![image](https://cloud.githubusercontent.com/assets/12628/14440340/0e1771b4-fff5-11e5-8519-fb8af6317bde.png)

i tried to keep this rather unobtrusive and not make assumptions about also toggling Sources view. once sources are shown, they are always shown, unless the user clicks the button.

**Comment by drJAGartner** [comment]
Fixed
