### ISSUE TITLE
Zoom in on click

### ISSUE THREAD

**Issue by drJAGartner** [Sotera/genie-ui#58]
On the event map, we should automatically zoom in on a cluster/set of clusters with the onclick event.

**Comment by lukewendling** [comment]
@drJAGartner it's a little hard to grab, but there is an invisible marker within the heatmap points that you can dbl click to zoom. good?

**Comment by drJAGartner** [comment]
What I'm envisioning with this is that you click an event from the list (on the right column), and it automatically zooms in to the event.

**Comment by lukewendling** [comment]
@drJAGartner added click to zoom + a hover 'preview' so you see a marker on the cluster before committing to zoom. on xgenie
