### ISSUE TITLE
Jitter Watchmen Locations

### ISSUE THREAD

**Issue by drJAGartner** [Sotera/genie-ui#62]
When a location is automatically generated via entity extraction, we need to add noise to the latitude and longitude so individual sources are discoverable.

**Comment by lukewendling** [comment]
@drJAGartner i fixed this for the ncmi data set. on data import. let's discuss further. i'm not sure if we need to build this into genie or if its moreso a data import issue.

**Comment by drJAGartner** [comment]
I think that if we enact it for watchmen, i.e. assigned locations, it should be sufficient.

**Comment by lukewendling** [comment]
closing
