### ISSUE TITLE
Review zoom level creation for events in the past

### ISSUE THREAD

**Issue by lukewendling** [Sotera/genie-ui#65]
Events should be plotted by their post date, on the time series graph in UI.

**Comment by justinlueders** [comment]
@lukewendling Did you fix this with your recent changes?  you decided it was best to plot them based on their end date right?

close this?

**Comment by lukewendling** [comment]
This was to do with maintaining zoom levels when sources are processed independently. They currently overwrite existing. Let's close for now and revisit later.
