### ISSUE TITLE
Populate bounding box prop for HashtagEventSource

### ISSUE THREAD

**Issue by lukewendling** [Sotera/genie-ui#66]
see EventSourceBase schema

sandbox events already contain a bounding_box prop. we need the same for hashtags.

the box should include all source tweets that comprise the event. we will draw a box in the UI around all tweets for a selected event.

@justinlueders @jreeme self-assign

**Comment by jreeme** [comment]
Added some code to the hashtag clusterer to get a bounding box around tweets for a given event.
