### ISSUE TITLE
End Date For Sandbox

### ISSUE THREAD

**Issue by drJAGartner** [Sotera/genie-ui#73]
We need to fix the end date for sandbox, I know Justin more or less had this done, but I just wanted an issue to make sure we test it.

**Comment by lukewendling** [comment]
@justinlueders close this?

cc @drJAGartner

**Comment by justinlueders** [comment]
@drJAGartner @lukewendling 

Yeah i think its working....at this point we need to stream in the data instead of pulling it all at once...but that is a new bug all together.

I say we close this
